name: Build & Deploy Front + Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #####################
      # FRONTEND (déjà buildé)
      #####################
      - name: Deploy frontend build
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend/build/*"
          target: "/home/ubuntu/projetCarte/frontend"

      #####################
      # BACKEND
      #####################
      - name: Deploy backend source
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "backend/*"
          target: "/home/ubuntu/projetCarte/backend"

      - name: Install backend & start with pm2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/projetCarte/backend
            npm install
            npm run migrate
            pm2 startOrRestart server.js --name backend || pm2 start server.js --name backend
